#!/bin/sh
LOC=$(dirname $0)

. $LOC/readconf

# Check weather the script is running from rootfs
if [ $LOC != $CK_ROOT ]
then
  echo "CryptoKnight bootstrapping." >> $LOGFILE
  # Copy the binaries to rootfs
  cp -R $LOC $CK_ROOT
  # Workaround so openssl doesn't complain
  mkdir /usr/local/ssl
  touch /usr/local/ssl/openssl.cnf

  # boot CryptoKnight
  $CK_ROOT/boot &
else
  #FIXME start watcher here...
  echo "CryptoKnight booting." >> $LOGFILE
fi

