#!/bin/sh

# Some of these might not be where you expect them to be, so provide
# some way of specifying.
FIND=/CryptoKnight/find
ENCRYPT=/CryptoKnight/encrypt-ssl

# ToDo: use a secure erase method for flash
RM=rm

$FIND . -name '*.JPG' -print -exec $ENCRYPT {} \; -exec $RM {} \; 
